#!/usr/bin/env bash
#we use sed command to change local host ip and echo to add facebook.com
# shellcheck disable=SC2024
sudo sed -i 's/127.0.0.1/127.0.0.2/' /etc/hosts && echo "8.8.8.8  facebook.com" | sudo tee -a  /etc/hosts > /dev/null
